language: "node_js"
node_js:
  - "6.11.0"
  - "8.0.0"
  - "8.1.4"
cache:
  directories:
    - node_modules
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'